# Generated by Django 2.2.12 on 2020-05-08 14:21

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19Triage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('msisdn', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('source', models.CharField(max_length=255)),
                ('province', models.CharField(choices=[('ZA-EC', 'Eastern Cape'), ('ZA-FS', 'Free State'), ('ZA-GT', 'Gauteng'), ('ZA-LP', 'Limpopo'), ('ZA-MP', 'Mpumalanga'), ('ZA-NC', 'Northern Cape'), ('ZA-NL', 'Kwazulu-Natal'), ('ZA-NW', 'North-West (South Africa)'), ('ZA-WC', 'Western Cape')], max_length=6)),
                ('city', models.CharField(max_length=255)),
                ('age', models.CharField(choices=[('<18', '<18'), ('18-40', '18-40'), ('40-65', '40-65'), ('>65', '>65')], max_length=5)),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('fever', models.BooleanField()),
                ('cough', models.BooleanField()),
                ('sore_throat', models.BooleanField()),
                ('difficulty_breathing', models.BooleanField(blank=True, default=None, null=True)),
                ('exposure', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not sure')], max_length=9)),
                ('risk', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=8)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_say', 'Rather not say')], default='', max_length=7)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('muscle_pain', models.BooleanField(blank=True, default=None, null=True)),
                ('smell', models.BooleanField(blank=True, default=None, null=True)),
                ('preexisting_condition', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not sure')], default='', max_length=9)),
                ('rooms_in_household', models.IntegerField(blank=True, default=None, null=True)),
                ('persons_in_household', models.IntegerField(blank=True, default=None, null=True)),
                ('completed_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('confirm_accuracy', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
    ]
