# Generated by Django 2.2.12 on 2020-05-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higher_health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid19triage',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='covid19triage',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='covid19triage',
            name='route',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='covid19triage',
            name='street_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
