# Generated by Django 2.2.12 on 2020-05-14 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('higher_health', '0002_auto_20200509_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.CharField(choices=[('ZA-EC', 'Eastern Cape'), ('ZA-FS', 'Free State'), ('ZA-GT', 'Gauteng'), ('ZA-LP', 'Limpopo'), ('ZA-MP', 'Mpumalanga'), ('ZA-NC', 'Northern Cape'), ('ZA-NL', 'Kwazulu-Natal'), ('ZA-NW', 'North-West (South Africa)'), ('ZA-WC', 'Western Cape')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='higher_health.University')),
            ],
        ),
    ]
