# Generated by Django 2.2.12 on 2020-05-14 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higher_health', '0003_campus_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid19triage',
            name='facility_destination',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('campus', 'Campus')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='covid19triage',
            name='facility_destination_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='higher_health.Campus'),
        ),
        migrations.AddField(
            model_name='covid19triage',
            name='facility_destination_province',
            field=models.CharField(blank=True, choices=[('ZA-EC', 'Eastern Cape'), ('ZA-FS', 'Free State'), ('ZA-GT', 'Gauteng'), ('ZA-LP', 'Limpopo'), ('ZA-MP', 'Mpumalanga'), ('ZA-NC', 'Northern Cape'), ('ZA-NL', 'Kwazulu-Natal'), ('ZA-NW', 'North-West (South Africa)'), ('ZA-WC', 'Western Cape')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='covid19triage',
            name='facility_destination_reason',
            field=models.CharField(blank=True, choices=[('staff', 'Staff'), ('student', 'Student'), ('visitor', 'Visitor')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='covid19triage',
            name='facility_destination_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='higher_health.University'),
        ),
        migrations.AddField(
            model_name='covid19triage',
            name='history_cardiovascular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='covid19triage',
            name='history_diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='covid19triage',
            name='history_hypertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='covid19triage',
            name='history_obesity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='covid19triage',
            name='history_other',
            field=models.SmallIntegerField(choices=[(1, 'YES'), (2, 'NO'), (3, 'MAYBE')], default=2),
        ),
    ]
