# Generated by Django 2.2.12 on 2020-05-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('higher_health', '0005_remove_duplicate_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covid19triage',
            name='history_other',
        ),
    ]
