# Generated by Django 2.2.12 on 2020-05-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higher_health', '0006_remove_covid19triage_history_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid19triage',
            name='taste',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
