# Generated by Django 2.2.12 on 2020-05-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('higher_health', '0007_remove_covid19triage_muscle_pain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'Campuses'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
    ]
