# Generated by Django 2.2.12 on 2020-05-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higher_health', '0007_remove_covid19triage_muscle_pain'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid19triage',
            name='facility_destination_campus_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='covid19triage',
            name='facility_destination_university_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
