# Generated by Django 2.2.12 on 2020-06-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('higher_health', '0008_university_other_char_fields'),
        ('higher_health', '0008_change_meta_options'),
    ]

    operations = [
    ]
