# Generated by Django 2.2.12 on 2020-06-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("higher_health", "0010_covid19triage_user")]

    operations = [
        migrations.AlterModelOptions(
            name="covid19triage", options={"ordering": ("timestamp",)}
        )
    ]
