# Generated by Django 2.2.12 on 2020-06-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('higher_health', '0009_merge_20200602_1111'),
        ('higher_health', '0011_auto_20200607_1120'),
    ]

    operations = [
    ]
