# Generated by Django 2.2.12 on 2020-06-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higher_health', '0012_merge_20200618_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='province',
            field=models.CharField(blank=True, choices=[('ZA-EC', 'Eastern Cape'), ('ZA-FS', 'Free State'), ('ZA-GT', 'Gauteng'), ('ZA-LP', 'Limpopo'), ('ZA-MP', 'Mpumalanga'), ('ZA-NC', 'Northern Cape'), ('ZA-NL', 'Kwazulu-Natal'), ('ZA-NW', 'North-West (South Africa)'), ('ZA-WC', 'Western Cape')], max_length=100),
        ),
    ]
