# Generated by Django 2.2.12 on 2020-06-29 08:56

from django.db import migrations
from django.core.exceptions import MultipleObjectsReturned


def create_other_university_campus_objects(apps, schema_editor):

    uni_model = apps.get_model('higher_health.University')
    campus_model = apps.get_model('higher_health.Campus')
    uni_kwargs = dict(name='Other', sort_order=1, province=None)

    try:
        uni_instance, created = uni_model.objects.get_or_create(
           **uni_kwargs
        )
    except MultipleObjectsReturned:
        uni_instance, created = uni_model.objects.filter(
            **uni_kwargs
        ).first()

    try:
        campus_model.objects.get_or_create(
            name='Other', university=uni_instance, sort_order=1
        )
    except MultipleObjectsReturned:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('higher_health', '0014_orderable_model'),
    ]

    operations = [
        migrations.RunPython(
            create_other_university_campus_objects)
    ]
