# Generated by Django 2.2.12 on 2020-06-29 08:56

from django.db import migrations


def create_other_university_campus_objects(apps, schema_editor):

    uni_model = apps.get_model('higher_health.University')
    campus_model = apps.get_model('higher_health.Campus')

    uni_instance, created = uni_model.objects.get_or_create(
        name='Other', sort_order=1
    )

    campus_model.objects.get_or_create(
        name='Other', university=uni_instance, sort_order=1
    )


class Migration(migrations.Migration):

    dependencies = [
        ('higher_health', '0014_orderable_model'),
    ]

    operations = [
        migrations.RunPython(
            create_other_university_campus_objects)
    ]
