# Generated by Django 2.2.24 on 2021-10-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higher_health', '0015_create_other_university_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid19triage',
            name='vaccine_uptake',
            field=models.CharField(blank=True, choices=[('PARTIALLY', 'Yes, partially vaccinated'), ('FULLY', 'Yes, fully vaccinated'), ('NOT', 'Not vaccinated')], default='', max_length=9),
        ),
    ]
